### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by derreck503**
Clarify the correct syntax for creating an ionic 2 project with a template.

### CODE REVIEW

**Comment by perrygovier** [comment]
thanks!

**Comment by derreck503** [comment]
Have a nice day Mr. Govier!

**Comment by mhartington** [comment]
This is actually intentional. The sentence was to show that if you dont pass a template, it will default to the tabs

**Comment by derreck503** [comment]
oh I see, I just had difficulty in knowing where to put the template
statement.

**Pull request merged**
