### PR TITLE
improve ionic-native docs

### PR DESCRIPTION
**Pull request by ihadeed**
- updated Native docs index
- clicking on `Native` takes you to the index instead of toggling menu

### CODE REVIEW

**Comment by mhartington** [comment]
Would you be able to add #646 to this PR as well? Then we can squash it all into one commit.

**Comment by ihadeed** [comment]
Sure .. just merged them together.

CircleCI was showing an error for a previous commit, saying that `elseif` is an unknown tag. Does jekyll have `elseif` statements ?

**Comment by ihadeed** [comment]
Oh I just looked it up. It's supposed to be `elsif` instead of `elseif`. Cancel that CircleCI build if you can, it's not needed.

**Comment by mhartington** [comment]
Added via https://github.com/driftyco/ionic-site/commit/eaec9b3a06d331398ae748043945d10c6c8f1df8

**Pull request closed without merging**
