### PR TITLE
Add the  documentation in ionic CLI /docs/cli/test.md

### PR DESCRIPTION
**Pull request by rbecheras**
This option wasn't documented at all yet.

(see https://github.com/driftyco/ionic-cli/issues/328)

### CODE REVIEW

**Comment by perrygovier** [comment]
The inline comment breaks JSON formatting too. Feel free to resubmit with the right property and commenting differently, but I'm going to close this for now.

**Comment by rbecheras** [comment]
Ok I will soon, thanks for responded

**Comment by bishwobhandari** [comment]
@nikmartin where do you add the defaultBrowser property at?

**Comment by nikmartin** [comment]
@bishwobhandari ionic.project. This is pretty old, I'm not sure this feature is still supported in the cli.

**Pull request closed without merging**
