### PR TITLE
docs(theming): add responsive utility documentation

### PR DESCRIPTION
**Pull request by brandyscarney**
This documents new attributes that will be added in the next framework release. They are not live yet so we should hold off on publishing this until they are. :smile:

### CODE REVIEW

**Comment by piotrowski** [comment]
Wasn't this released with v3.1?

**Comment by brandyscarney** [comment]
Yes these have all been added in the framework, @perrygovier good to merge?

**Comment by mhartington** [comment]
LGTM, I say it's safe to merge

**Comment by brandyscarney** [comment]
Thanks @mhartington :)

**Pull request merged**
