### PR TITLE
Update ngx-translate guide for lazy loading pages

### PR DESCRIPTION
**Pull request by MTechDE**
I updated the guide to show how to use ngx-translate together with Ionics lazy loading pages

### CODE REVIEW

**Comment by mhartington** [comment]
Added, thanks!

**Comment by rebelholic** [comment]
@danielsogl your old guide not compatible with ionic 3.3.0 (latest version), please update again and please give a example repo.

**Comment by danielsogl** [comment]
@rebelholic Can you explain what does not work? If you check out the super-starter repo, it is working well with Ionic 3.3.

**Comment by rebelholic** [comment]
Its my code for "app.module.ts" below:

```
import { BrowserModule } from '@angular/platform-browser';
import { ErrorHandler, NgModule } from '@angular/core';
import { IonicApp, IonicErrorHandler, IonicModule } from 'ionic-angular';
import { TranslateModule, TranslateLoader }  from '@ngx-translate/core';
import { TranslateHttpLoader } from '@ngx-translate/http-loader';
import { HttpModule } from '@angular/http';
import { MyApp } from './app.component';

export function createTranslateLoader(http: HttpModule) {
  return new TranslateHttpLoader(http, './assets/lang/', '.json');
}

@NgModule({
  declarations: [
    MyApp,
  ],
imports: [
    BrowserModule,
    HttpModule,
    IonicModule.forRoot(MyApp),
     TranslateModule.forRoot({
      loader: {
        provide: TranslateLoader,
        useFactory: (createTranslateLoader),
        deps: [HttpModule]
      }
    })
  ],

```
Got error message like below:
error

So how I can fix it?

**Comment by danielsogl** [comment]
@rebelholic I see the error.

Change your http imports to this

`import { HttpModule, Http } from '@angular/http';`

**Comment by rebelholic** [comment]
Thanks its already fixed

**Comment by krushn** [comment]
Translate Pipe not working in Modal any idea please help?

**Comment by mg1075** [comment]
This is getting confusing with Angular 4.3 in the mix. 
Do there need to be two sets of instructions now, one for pre-4.3, and one for 4.3 and onward?

**Comment by Gajendrasinh** [comment]
app.module.ts

this is part of my code, only load en.json files not load jp.json file

 this.storage.set('language', 'en');

 translate.addLangs(['en', 'jp']);
 translate.setDefaultLang('en');

 translate.use('en');

import { HttpModule, Http } from '@angular/http';
import { TranslateModule, TranslateLoader} from '@ngx-translate/core';
import { TranslateHttpLoader } from '@ngx-translate/http-loader';
import { HttpClient, HttpClientModule } from '@angular/common/http';


// AoT requires an exported function for factories
export function exportTranslateStaticLoader(http : HttpClient) {
  return new TranslateHttpLoader(http, './assets/i18n/', '.json');
}
  imports: [
IonicModule.forRoot(MyApp),
TranslateModule.forRoot({
      loader: {
          provide: TranslateLoader,
          useFactory: exportTranslateStaticLoader,
          deps: [HttpClient]
        }
    }),
]

**Pull request closed without merging**
