### PR TITLE
Changed ToastController to Toast

### PR DESCRIPTION
**Pull request by sthomasme**
ToastController not working

### CODE REVIEW

**Comment by mhartington** [comment]
This is incorrect as of beta 11. Please see the beta 11 changelog

**Comment by sthomasme** [comment]
i am using beta 25

**Comment by mhartington** [comment]
That is the CLI version, not the version of ionic-angular. Please see your package.json 


http://ionicframework.com/docs/v2/resources/using-npm/

**Comment by sthomasme** [comment]
OK. Its beta 9. Thanks

**Pull request closed without merging**
