### PR TITLE
Add new book to resources section

### LINKED ISSUE #1110: Add new book to Resources - Hybrid Mobile Development with Ionic
https://www.packtpub.com/application-development/hybrid-mobile-development-ionic

### PR DESCRIPTION
**Pull request by bdeanindy**
This should resolve #1110

### CODE REVIEW

**Comment by perrygovier** [comment]
lgtm, note this is "below the fold". it won't be visible unless in the books section.

**Comment by bdeanindy** [comment]
I can adjust it to be above the fold (I see, you mean this (right):

```
191       <li ng-show="hash != 'books'">
192         <a href="#books" ng-click="hash = 'books'">More Books...</a>
```

**Comment by perrygovier** [comment]
yeah, you'd want to move _it_ up above that line, move another book to be below the fold and update the tags on each of the `li`s to match their respective new place.

**Comment by bdeanindy** [comment]
I'll pull and make the change, then push it.

**Comment by bdeanindy** [comment]
Any recommendations on which book should be moved down @perrygovier @mhartington @bensperry ???

**Comment by perrygovier** [comment]
@mhartington would know best

**Comment by bdeanindy** [comment]
@perrygovier Are we only ever allowed to have 6 books above the fold?

**Comment by perrygovier** [comment]
it's an arbitrary number ben and I decided was how many you can have in the index list before things looked cluttered

**Comment by bdeanindy** [comment]
Gotcha. Thanks.

**Comment by bdeanindy** [comment]
Hey @gauravsaini03 Please see #1112 PR for the resolution to this. :)

**Comment by gauravsaini03** [comment]
@bdeanindy :+1: Thanks for moving it upwards.

**Pull request merged**
