### PR TITLE
In complete Statusbar usage syntax

### PR DESCRIPTION
**Pull request by ankurvr**
Just completed statusbar syntax.
It is not available on live site documentations.

Problem is here [Status Bar Page](http://ionicframework.com/docs/v2/native/Status%20Bar/)

### CODE REVIEW

**Comment by mhartington** [comment]
Thanks, but this is not the correct place to be making changes to the ionic-native API docs.

**Comment by ankurvr** [comment]
Then can you tell me the place where i can suggest changes?

**Comment by mhartington** [comment]
https://github.com/driftyco/ionic-native/blob/master/src/plugins/statusbar.ts

**Comment by ankurvr** [comment]
Actually there are two pages for Status bar plugin

http://ionicframework.com/docs/v2/native/status-bar/
http://ionicframework.com/docs/v2/native/Status Bar/

Second page is coming from search on page and first is from left side bar.

**Pull request closed without merging**
